server:
  address: 0.0.0.0
  port: ${PORT:8380}
  servlet:
    session:
      timeout: 2h
      cookie:
        http-only: true
        same-site: lax

spring:
  application:
    name: webpage-navigation-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-tanyouwei.alwaysdata.net:3306/tanyouwei_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: tanyouwei
    password: 980704Bin.
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 1
      maximum-pool-size: 5
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.tanwb.navigation.mapper: debug
    com.baomidou.mybatisplus: debug
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari.pool.HikariPool: debug

app:
  cors:
    allowed-origins:
      - http://localhost:5500
      - http://127.0.0.1:5500
      - http://localhost:8381
      - http://127.0.0.1:8381
      - https://tanyouwei.alwaysdata.net/
      - https://mryouwei.github.io/DaoHang/
      - https://mryouwei.github.io/webpage-navigation/
      - http://mryouwei.github.io/webpage-navigation/
      - https://api-proxy-15501548642248.workers.dev/
      
